name: lint
on:
  pull_request: {}
  push:
    branches:
      - master
      - main

jobs:
  test:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      # Setup repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.25'

      - name: Install buf
        uses: bufbuild/buf-setup-action@v1.50.0
        with:
          version: "1.64.0"

      - name: gRPC proto definitions compilation
        run: make deps

      # Check format
      - run: make check-fmt

